### ISSUE TITLE
The refineDet trained model can be used?

### ISSUE THREAD

**Issue by nguoer121** [Stick-To/RefineDet-tensorflow#3]
Hi, I trained the RefineDet-tensorflow clode by the VOC2007 train_dataset,  But when I test the voc test_dataset, I can't get any checkboxes,  I only remove the two variables(zoom_size and crop_method) of the "image_augmentor_config",  Did you succeed by your  code of the RefineDet-tensorflow?

**Comment by Stick-To** [comment]
If you change the weights of four part losses in the end of function _compute_one_image_loss() in RefineDet.py,  the model will be easier to converge, which is not mentioned in original paper. And change the iou threshold of pos and neg examples may helpful too.
