### ISSUE TITLE
May I ask training data type?

### ISSUE THREAD

**Issue by wulungching** [Stick-To/RefineDet-tensorflow#9]
Hi @Stick-To ,

Thanks for your reply, I have changed VGG to mobileNetV1 already.
And I also change input size to 300x400 and then get graph successfully.

But when I want to train networks by my dataset, it occurs error.
` 2019-08-21 15:28:58.893031: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Feature: ground_truth (data type: string) is required but could not be found.
 File "testRMSSD.py", line 71, in <module>
    mean_loss = RMSSD.train_one_epoch(lr)
  File "/home/wlching/github/Object-Detection-API-Tensorflow/RMSSD.py", line 506, in train_one_epoch
    _, loss = self.sess.run([self.train_op, self.loss], feed_dict={self.lr: lr})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Need minval < maxval, got 0 >= 0
	 [[{{node random_uniform_1}} = RandomUniformInt[T=DT_INT32, Tout=DT_INT32, seed=0, seed2=0](random_uniform_1/shape, random_uniform_1/min, random_uniform_1/max)]]
	 [[node IteratorGetNext (defined at /home/wlching/github/Object-Detection-API-Tensorflow/RMSSD.py:66)  = IteratorGetNext[output_shapes=[[32,?,?,?], [32,?,5]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
	 [[{{node IteratorGetNext/_25}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_5_IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]`

May I ask training data format like this is ok?

> train_20190819_flag190326.record-00000-of-00010  train_20190819_flag190326.record-00004-of-00010  train_20190819_flag190326.record-00008-of-00010
train_20190819_flag190326.record-00001-of-00010  train_20190819_flag190326.record-00005-of-00010  train_20190819_flag190326.record-00009-of-00010
train_20190819_flag190326.record-00002-of-00010  train_20190819_flag190326.record-00006-of-00010
train_20190819_flag190326.record-00003-of-00010  train_20190819_flag190326.record-00007-of-00010

I used testrefinedet.py and change training data as my own tfrecord, and it gave same error message.

**Comment by Stick-To** [comment]
it need voc format  dataset, and generate tfrecord by utils.test_voc_utils.py

**Comment by Stick-To** [comment]
![捕获](https://user-images.githubusercontent.com/34546552/63417041-24208d00-c433-11e9-9bcc-80aee454ded5.PNG)

**Comment by wulungching** [comment]
> it need voc format dataset, and generate tfrecord by utils.test_voc_utils.py

Could I possible use my own tfrecod file?

**Comment by Stick-To** [comment]
no ， the parse_function could not understand it

**Comment by wulungching** [comment]
> no ， the parse_function could not understand it

OK~ thanks for your reply!

**Comment by wulungching** [comment]
I download VOC dataset and follow your step and I can successfully train model now.
I would try to modify parse_function to my own tfrecord format, thanks! :D

**Comment by wulungching** [comment]
Hi @Stick-To ,

Unfortunately, it had some problem randomly.
Do you know how to solve this problem?
[https://ppt.cc/fsHQcx](url)

**Comment by Stick-To** [comment]
delete 'zoom_size' in image_augmentor_config

**Comment by wulungching** [comment]
> delete 'zoom_size' in image_augmentor_config

It seems work now!! Thanks a lot~
